In [1]:
#import các thư viện cần thiết
import pandas as pd
import numpy as np
import re

In [2]:
#đọc file csv
df = pd.read_csv("../data/Amazon-Products_processed.csv")
df_feature = df.copy()

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 334961 entries, 0 to 334960
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   name                334961 non-null  str
 1   main_category       334961 non-null  str
 2   sub_category        334961 non-null  str
 3   image               334961 non-null  str
 4   link                334961 non-null  str
 5   ratings             334961 non-null  float64
 6   no_of_ratings       334961 non-null  int64
 7   discount_price      334961 non-null  float64
 8   actual_price        334961 non-null  float64
 9   actual_price_vnd    334961 non-null  float64
 10  discount_price_vnd  334961 non-null  float64
 11  discount_percent    334961 non-null  float64
 12  price_range         334961 non-null  str
dtypes: float64(6), int64(1), str(6)
memory usage: 33.2 MB

In [4]:
#khởi tạo list
text_columns = [
    "name",
    "main_category",
    "sub_category"
]

In [5]:
#đưa vể lowercase
for col in text_columns:
    df_feature[col] = (
        df_feature[col]
        .astype("string")
        .str.lower()
    )

In [6]:
#xóa khoảng trắng thừa
for col in text_columns:
    df_feature[col] = (
        df_feature[col]
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
    )

In [7]:
#xóa kí tự đặc biệt
def clean_text(text):
    text = str(text).lower()

    # Xóa các ký hiệu thương mại
    text = re.sub(r"[®©™]", "", text)

    # Chuẩn hóa khoảng trắng
    text = re.sub(r"\s+", " ", text)

    return text.strip()

for col in text_columns:
    df_feature[col] = df_feature[col].apply(clean_text)

In [8]:
#tạo product_id
df_feature = df_feature.reset_index(drop=True)
df_feature["product_id"] = df_feature.index
df_feature[
    [
        "product_id",
        "name"
    ]
].head()

   product_id                                               name
0           0  lloyd 1.5 ton 3 star inverter split ac (5 in 1...
1           1  lg 1.5 ton 5 star ai dual inverter split ac (c...
2           2  lg 1 ton 4 star ai dual inverter split ac (cop...
3           3  lg 1.5 ton 3 star ai dual inverter split ac (c...
4           4  carrier 1.5 ton 3 star inverter split ac (copp...

In [9]:
#tạo product_text
df_feature["product_text"] = (
    "Product: " + df_feature["name"] +
    ". Main category: " + df_feature["main_category"] +
    ". Sub category: " + df_feature["sub_category"]
)

df_feature[
    [
        "product_id",
        "product_text"
    ]
].head()

   product_id                                       product_text
0           0  Product: lloyd 1.5 ton 3 star inverter split a...
1           1  Product: lg 1.5 ton 5 star ai dual inverter sp...
2           2  Product: lg 1 ton 4 star ai dual inverter spli...
3           3  Product: lg 1.5 ton 3 star ai dual inverter sp...
4           4  Product: carrier 1.5 ton 3 star inverter split...

In [10]:
df_feature.info()

<class 'pandas.DataFrame'>
RangeIndex: 334961 entries, 0 to 334960
Data columns (total 15 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   name                334961 non-null  str
 1   main_category       334961 non-null  str
 2   sub_category        334961 non-null  str
 3   image               334961 non-null  str
 4   link                334961 non-null  str
 5   ratings             334961 non-null  float64
 6   no_of_ratings       334961 non-null  int64
 7   discount_price      334961 non-null  float64
 8   actual_price        334961 non-null  float64
 9   actual_price_vnd    334961 non-null  float64
 10  discount_price_vnd  334961 non-null  float64
 11  discount_percent    334961 non-null  float64
 12  price_range         334961 non-null  str
 13  product_id          334961 non-null  int64
 14  product_text        334961 non-null  str
dtypes: float64(6), int64(2), str(7)
memory usage: 38.3 MB

In [11]:
df_feature.to_csv(
    "../data/Amazon-Products_feature.csv",
    index=False
)